### ISSUE TITLE
Autofilling may lead to a bug that makes local users cannot login

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#121]
When **changing status** for a local user, the user's **password will be changed** and then he could not login again. 

@PedroLiu

**Comment by PedroLiu** [comment]
I tried several times, can login with current password.
If e-mail is blank, will meet a 500 error.
When will this bug happen?

**Comment by leebaok** [comment]
It happens when **root** changes status of a local user. And the local user's password changes.

**Comment by PedroLiu** [comment]
I find a local account on iwork, changed it several times, didn't trigger that bug.
Maybe I will find it on my own computer?will try

**Comment by leebaok** [comment]
which user did you use for test on iwork ?

**Comment by PedroLiu** [comment]
docklet
password is docklet

**Comment by leebaok** [comment]
1. use root to set docklet with password:docklet and status:init
2. login with docklet/docklet -- OK
3. use root to set docklet with status:applying
4. login with docklet/docklet -- failed

@PedroLiu

**Comment by PedroLiu** [comment]
Inspected with @leebaok ,  nothing wrong with the code.
Maybe the browser's auto-filling lead to this bug.
Will move password modifying function to another panel(initially there is a independent method)

**Comment by leebaok** [comment]
Auto-filling is common nowadays. ( when you have saved password in browser, it will auto fill password field in web pages. )

So, password changing should be put in independent page.

**Comment by PedroLiu** [comment]
Solved,  a version with a safer password changing is on my fork, I will merge it into unias/docklet when I finish another issue
