### ISSUE TITLE
Jupyter has incompatibility problem on 360browser

### ISSUE THREAD

**Issue by Huayet** [unias/docklet#147]
Jupyter页面，使用360浏览器有兼容问题。
·无论是Chrome还是IE模式，都显示Not connected。
·调试显示请求/api/kernels/的websocket失败（Provisional headers are shown）。

**Comment by caodg** [comment]
Yes, it has some problems with IE/Edge family browsers. Currently we have to wait for Jupyter team resolve this issue. Thank you very much.
