### ISSUE TITLE
check typing and input on web pages and web server

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#20]
We should check whether typing on web pages is valid.  
And checking input of web server is necessary.

For example, user may name workspace 'My Homepage no.1'. But space character is not valid for workspace name. This may cause user unable to start workspace.

**Comment by PedroLiu** [comment]
Will do.
Check the typing of name, e.g. workspace name, image name.
The same as variable names in C++.

**Comment by PedroLiu** [comment]
Done, see pull request #60
