### ISSUE TITLE
bug of external login 

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#25]
external login failed and nothing output

**Comment by leebaok** [comment]
This bug is already fixed.

**Please test your code before sending pull request !!!**

**Comment by caodg** [comment]
@PedroLiu  made the modification for not logging user passwd, but he may not tested it for iaaa plugin. so @PedroLiu needs to check it works in any cases as expected.

**Comment by caodg** [comment]
will close this issue, and reopen #12  @PedroLiu
