### ISSUE TITLE
Refine container job creation

### ISSUE THREAD

**Issue by wwt17** [unias/docklet#392]
https://github.com/unias/docklet/blob/5c1a55964a61109023b429e6756ec2cd64bdd976/src/worker/taskcontroller.py#L354
It's better to replace the `subprocess.Popen` here by `subprocess.run(..., timeout=timeout)`. Benifit: No need to use `while` for timing. Timing becomes more precise, efficient and elegant.

**Comment by FirmlyReality** [comment]
It's a good advice. We'll accept it. Thanks~
