### ISSUE TITLE
Any chance updating this to use LXD 

### ISSUE THREAD

**Issue by bmullan** [unias/docklet#403]
Any chance updating this to use LXD instead of or in addition to LXC ?

www.linuxcontainers.org

**Comment by iteratorlee** [comment]
Thanks for your advice. We will consider that. By the way, your contribution is welcomed.

**Comment by bmullan** [comment]
@iteratorlee 

I'd be glad to help where I can.
Unfortunately I am not a programmer but I am a long time Ubuntu and LXC/LXD user.

I am the Moderator of the LXD and LXC sub-reddits:

**[LXD sub-reddit](https://www.reddit.com/r/LXD/)**

**[LXC sub-reddit](https://www.reddit.com/r/LXC/)**

I am also fairly good at Bash scripting as my own GitHub project [CIAB Remote Desktop System](https://github.com/bmullan/ciab-remote-desktop) _is built/integrated using Bash Scripting_ and includes:    Guacamole, Tomcat, MySQL, NGINX, XRDP, LXD
