### ISSUE TITLE
Fail to create container

### ISSUE THREAD

**Issue by FirmlyReality** [unias/docklet#49]
After starting the master and worker, it is reported by master that "container created failed". And in the worker's log, it is reported that there is an error at line 133 in "container.py".  The log is "ERROR container[133] 'disk' ".

**Comment by FirmlyReality** [comment]
To fix the bug, we should add some codes in "guest_control.py" at about line 28 like this:
`user_info["data"]["groupinfo"]["disk"] = 2000 `

**Comment by zhongyehong** [comment]
Done
