### ISSUE TITLE
display quota in Status page

### ISSUE THREAD

**Issue by caodg** [unias/docklet#5]
show user's quota information in their status pages.

**Comment by caodg** [comment]
should display more quota information, like disk quota, images number quota, etc.. and 1 core should not be 100.00% Cores, but 1 core, 2 cores, 3 cores ...

**Comment by caodg** [comment]
Even the user has not created a workspace, the status page should still display the quota of the user. That is to say, the displaying of quota information is independent of displaying cluster information.

Now @zhongyehong has submitted new code about user guota, so you @FirmlyReality can get these info easily.

**Comment by FirmlyReality** [comment]
Done. Please check if it meets the need.

**Comment by caodg** [comment]
have replied you in your Pull Requests. need a minor fix.
