### ISSUE TITLE
vlanid share

### ISSUE THREAD

**Issue by zhongyehong** [unias/docklet#51]
the user in fundation group should share vlanid

**Comment by zhongyehong** [comment]
Done

**Comment by zhongyehong** [comment]
When use this version, please use init mode to start master

**Comment by caodg** [comment]
how could we init master if there are already some users using workspaces , like in iwork ?

**Comment by zhongyehong** [comment]
I will move the code of initial shared vlanid to start mode later

**Comment by caodg** [comment]
Yes, the existing users should not be affected. therefore, when restarting docklet, old users are treated as old, and new users will be added in foundation group.

btw, can the admin set default group now ?
