### ISSUE TITLE
Show disk usage in Summary of container

### ISSUE THREAD

**Issue by caodg** [unias/docklet#55]
Current **Status** table  is : 

Current Status:

Name |	State |	IP Address |	CPU Use	 | CPU Quota	| Mem Use 
----      |     ----    |   -----               |  ----          | ----   | ----
 0006175153-30-0	| Running	 | 172.16.0.54	 | 78.63 seconds | 	2 Cores	 | 0.80% (122.45MiB/15258.79MiB)

could be

Current status of 0006175153-30-0:

     State |	IP Address |	CPU Usage	 | Mem Usage  |  Disk Usage
      ----    |   -----               |  ------          | ---------   | ----
  Running	 | 172.16.0.54	 | 78.63 seconds (2 Cores)	 | 0.80% (122.45MB/15258.79MB) | 60% (1200MB/2000MB)

**Comment by FirmlyReality** [comment]
Done.
