### ISSUE TITLE
[monitor] status page of normal user failed

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#57]
status page of normal user failed.

I have saw the code of httprest.py and **the bug is in line 348 ~ line 380**.
 
**The code below self.response will be executed also, except you put return after self.response.**

For normal user, status page will request httprest with /monitor/user/quotainfo, I think line 349 of httprest.py should be executed but line 355 should not be executed. Right? So, you should fix this soon. 

@FirmlyReality

**Comment by FirmlyReality** [comment]
Done.
