### ISSUE TITLE
add quota easily and able to remove quota group

### ISSUE THREAD

**Issue by caodg** [unias/docklet#6]
- [x]  can remove a quota group
- [x]  can add quota with just one click with no need to edit the detailed quota item

**Comment by zhongyehong** [comment]
Done

**Comment by caodg** [comment]
yes it works. but the Delete button is ugly. Is it possible to use only public buttons: Create, Edit, Delete selected items?

**Comment by zhongyehong** [comment]
Done

**Comment by caodg** [comment]
good work.

**Comment by caodg** [comment]
I reopen this issue for two reasons:
1. The table Admin - Quota  uses **Bold** font, should be normal font.
2. There should be an nfs quota item, i.e., the disk size the user can have in their global data directory.

**Comment by caodg** [comment]
@zhongyehong 

I just tested your code, sadly it failed.

Two problems:

1. The **data** field should have a default value, e.g., 100. Currently it is blank.
2. Can not change default group.  Get error message 

```
simplejson.scanner.JSONDecodeError
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zhongyehong** [comment]
1.You can set the value of data in admin page, Is this a problem? I will add default value in upgrade.py later.
2.This problem due to PedroLiu rewrite the httprest.py, I use getvalue method of form before, now should be get, I will fix it soon.
3.About the Bold font, I don't know why it is Bold. I write it the same as other table, but only admin page has this problem.

**Comment by caodg** [comment]
1. A default value is better.

2. About upgrade.py, I think it is a bit professional. But, it could be more professional. For example, check the version of original system and determine the upgrade actions. Since we will have many releases, there should be many upgrade actions, each could be very different.  This could be done in the future.

**Comment by caodg** [comment]
About the commits of #89 , the docklet.conf.template could be changed to 

Also you need to change code accordingly, especially NO changed to False, YES changed to True

```
# DATA_QUOTA : whether enable the quota of data volume or not
# True or False, default: False
# DATA_QUOTA=False

# DATA_QUOTA_CMD : the cmd to set the quota of a given directory. It accepts two the arguments:
# arg1: the directory name, relative path from the data volume root, e.g, "/users/bob/data"
# arg2: the quota value in GB of string, e.g., "100"
# default: "gluster volume quota docklet-volume limit-usage %s %s"
# DATA_QUOTA_CMD="gluster volume quota docklet-volume limit-usage %s %s"
```

**Comment by zhongyehong** [comment]
Done
