### ISSUE TITLE
enhance quota management

### ISSUE THREAD

**Issue by caodg** [unias/docklet#7]
quota management enhancements
- [ ]  more quota item, like disk quota.
- [ ]  save quota information in separate json file

**Comment by zhongyehong** [comment]
Done

**Comment by caodg** [comment]
When admin edit the quota group, they may not know how to input the value. A nice method is to give example value and brief introduction (hint) in the input field. For example, for **disk**, the hint could be "the disk quota of container, e.g, 500M or 1G"; for **memory**, cloud be "the memory quota of container, e.g., 500M or 4G".

When adding a new quota, could also add a filed of "Hint", as described above.

**Comment by zhongyehong** [comment]
Done, when use this version, please remove the /opt/docklet/global/sys/quota
