### ISSUE TITLE
Big File Upload

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#70]
Big File Upload for OS practice

**Comment by nsknojj** [comment]
!!

**Comment by nsknojj** [comment]
zhangwentao

**Comment by nsknojj** [comment]
zhangwentao

**Comment by nsknojj** [comment]
Some notes after reviewing code:
https://github.com/nsknojj/notebook_task/tree/master/notes

**Comment by caodg** [comment]
@nsknojj 
I recommend you writing notes using markdown format, which could be automatically rendered as HTML format.

**Comment by nsknojj** [comment]
I just figure out what I should do. I need to change the php server "Jquery-file-upload" provided  to a new server side with "tornado" framework. Big file upload uses post method with "Content-Type: multipart/form-data". Luckily, it is well-supported by tornado.

**Comment by leebaok** [comment]
Maybe implementing the backend in tornado is more complex. 

You can use one apache/php server for all users. The server puts every file to the correct user's directory. In this way, you just need to pass username to server from browser and then the server gets the username and puts the file in the right path. 

But maybe implementing the backend in tornado is not so complex. I noticed there is a GAE python example of backend in source code. And it is not complex. So this method is also ok.

Which way ? Up to you. 

Go ahead.

**Comment by caodg** [comment]
I prefer using tornado. 
The problem of using Apache server is that we have to set up the server just for file uploading. However, the other functions, like downloading, previewing, are all supported by tornado. That will confuse developers and administrators.
If uploading function is provided by tornado, then we do not have to bother setting up a third apache server.

**Comment by nsknojj** [comment]
Today, I have implemented the basic Multi-Blob upload function in tornado server side,
https://github.com/nsknojj/notebook_task/blob/master/handlers.py
In this version, the upload file is saved in current directory, and the response of POST is incorrect.

**Comment by nsknojj** [comment]
Almost completed
https://github.com/nsknojj/notebook/tree/big-upload
