### ISSUE TITLE
recording the user's historical resource usage

### ISSUE THREAD

**Issue by caodg** [unias/docklet#72]
We need to periodically record the resource usage of the user's all containers, especially the CPU usage.
Note that for a container named **ct**, if we stop it and restart it, the *lxc-info -n ct* command will only get the current usage info from the restarting time. The previous history usage info will get lost. So we need a deliberate design to record all the historical resource usage.

@FirmlyReality 
@leebaok @zhongyehong @monumentality

**Comment by ghostplant** [comment]
git clone https://github.com/unias/dockmeter.git
cd dockmeter
sudo ./main.py
-------------------------
curl -L -X POST -F uuid=[lxc-name] http://0.0.0.0:1729/v1/billing/increment
