### ISSUE TITLE
time display in UserList

### ISSUE THREAD

**Issue by caodg** [unias/docklet#86]
The register date displayed seems to be in UTC time, which is not convenient for non UTC timezone users. @PedroLiu 

The image save time and workspace start time is using EastAsia/Shanghai timezone, which is possibly the default setting of the physical host. 

So @PedroLiu  should at least display the time using default timezone. 

And maybe we should let admin specify timezone docklet uses, then show time according to this timezone? @zhongyehong

**Comment by PedroLiu** [comment]
I used the function datetime.utcnow() to get current time, I can replace it with datetime.now(), which returns the time of the host.

**Comment by PedroLiu** [comment]
Done, see pull request #183
