### ISSUE TITLE
Any change to user info will cause an error

### ISSUE THREAD

**Issue by PedroLiu** [unias/docklet#93]
Error info is below.
 File "/home/liupd/docklet/src/userManager.py", line 619, in modify
    self.set_nfs_quota(user_modify.username,res['data']['data'])
KeyError: 'data'

@zhongyehong , Please fix it

**Comment by zhongyehong** [comment]
You should set the data value in admin page, e.g 100

**Comment by PedroLiu** [comment]
If I install docklet without any extra configuration, is this a bug I will meet in any conditions?
I will add some code to report this reason to admin.

**Comment by zhongyehong** [comment]
No need, I will add default value in upgrade.py later.

**Comment by caodg** [comment]
@zhongyehong 

It is a bug, should be fixed in main code.
It is unreasonable to have to  run upgrade.py for a fresh install. 
The data field should have a default value, which can work for a default installation.

Upgrade.py should only be used for an already running install.

**Comment by zhongyehong** [comment]
If you first time to install docklet, the default values of all quota will be set, include data quota.
The problem is  I add the data quota in upgrade.py, without setting default value of exists quota group, so I mean I will fix it.

**Comment by zhongyehong** [comment]
Done
